#!/bin/bash
#set -euo pipefail

function abspath {
    if [[ -d "$1" ]]
    then
        pushd "$1" >/dev/null
        pwd
        popd >/dev/null
    elif [[ -e $1 ]]
    then
        pushd "$(dirname "$1")" >/dev/null
        echo "$(pwd)/$(basename "$1")"
        popd >/dev/null
    else
        echo "$1" does not exist! >&2
        return 127
    fi
}

scriptdir=$(cd $(dirname $0) && pwd)
source "$scriptdir/env"
entry_file_relative_path=$1
entry_file_path=$(abspath $entry_file_relative_path)
entry_file_name=$(basename $entry_file_path)
entry_base_file_name="${entry_file_name%.*}"

# build-and-run on entry
sh $scriptdir/build-and-run $entry_file_path

fswatch -o $entry_file_path | (while read; do sh $scriptdir/build-and-run $entry_file_path; done)
